### ISSUE TITLE
OIP-3: eWallet address format

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/OIP#3]
# Summary

Currently addresses are stored as UUID for wallets in the eWallet. This format is not really suited and was only meant as a temporary format. This OIP explores a few solutions to replace it with something more appropriate.

# Specification

I'm not sure which one is best, but here are 7 formats that @unnawut and I came up with:

## 1. UUID 

The first option is to keep it as is, but UUID are long, hard to type (including the dashes, and all the alphanumeric characters) and can't be copied with one click (which is something I'd like to see in the new format).

## 2. ULID

The second option is pretty simple: we use the same format used for every external ID in the eWallet. The format for addresses would look like `adr_01ca2p8jqans5aty5gj5etmjcf`.

Still hard to type for a user and a bit too long, also contains both letters and numbers.

## 3. xxxx_332493849383

Third option is using 16 characters (4 letters + 12 digits) to have a format that looks like `abcd_111122223333` and could be shown to the user as `abcd-1111-2222-3333` with 4 cases to fill (giving the same feeling as credit card, minus the 4 characters at the beginning). 

Why use those 4 characters? To increase the potential number of addresses.

10^16 = 1E16 possibilities
4^26 * 10^16 = 4.56976E21 possibilities

4 characters are easy to remember and 12 digits is just two more than a phone number so with this, I believe anyone should be able to remember their address.

## 4. `this-is-my-address-yo` (or `something-dirty`... 👎  )

Another option is to use either an auto-generated "passphrase:" with 3 to 5 words that would be used as an address. An added feature or alternative would be to allow users to enter their own passphrase address (but we'd probably end up with stupid and obcene ones...)

## 5. vvvv-mmmm-uuuu-uuu-c (3324-3239-8328-8438)

Credit card style, with digits for vendor identifier, user identifier, and check digit.

## 6. 324-3-234-1344

Bank account style (Thailand). What people are used to in Thailand.

# More options?

If you guys have more ideas and think we should go with one of the format, let me know! I don't think there's a right answer, they all have their pros and cons, but let's try to find the best one for us!

**Comment by whoisjeremylam** [comment]
Some considerations that I can think of that may influence the decision.

1. What are the consequences of a user entering an eWallet address incorrectly? In the crypto world, funds could be sent to an unspendable address.

1. Easier to type addresses have the tendency to have a lower global uniqueness. It becomes easier to accidentally type in someone else's valid address.

The two above points would be mostly 

Option #3 + check digits is relatively good balance. Reminds me of https://en.wikipedia.org/wiki/International_Bank_Account_Number.

I think it's a great idea that @T-Dnzt mentioned where non-alphanumeric characters and whitespace could validly input by the user and subsequently stripped out.

**Comment by T-Dnzt** [comment]
@whoisjeremylam 

1. If the address exists, the funds would be sent there. If it doesn't, the transaction would fails and no value would be sent. Adding a confirmation step where the owner of the receiving wallet is shown (either the receiving account name or the receiving user's username) could actually be done pretty easily right now to reduce the chance for wrong addresses (like bank transfers basically).

2. True! We need to find the right balance :)

I also like #3 and adding a check digit would be good (Just not sure how we can do it since we have letters there and the check digit on credit card is using calculations to generate it). Any idea? Only do it on the numeric part or use a different algorithm?

**Comment by whoisjeremylam** [comment]
Was doing a little searching and the check digit calculation that IBAN uses is defined in [ISO 7064](https://www.iso.org/standard/31531.html).

We should be able to find our answer there!

**Comment by unnawut** [comment]
I'm inclined towards these two:

**1 .`abcd_nnnnnnnnnnnn`**

Pros:
  - Supports even more addresses than credit card number format.
  - Allows a bit of playful UX help. E.g. `ghub-1234-5678-9012`, `omgo-1234-5678-9012`, `appl-1234-5678-9012`.

Cons:
  - Letters are harder to type than numbers (subjective).
  - Easier to abuse? Scammers could target by using 4-letter to misrepresent wallets of a large brand that they do not own?

**2. `vvvv-vvuu-uuuu-uuuc`**

Pros:
  - Numbers only. Numeric keyboard on mobile. Also easy typing with numpads.
  - General public are aware of this format and knows instantly it's to do with an account.

Cons:
  - Clash with credit card numbers. There are policies regarding storing, displaying and transmitting credit card numbers for those dealing with credit cards. This risks the confusion if it's a credit card number or a wallet address and probably will cause a lot of headache for all types of ewallet providers.
  - Confusion with credit cards anyway even without the policies/regulations.

-----

**Other considerations:**

- I'm assuming we will neglect non-alphanumeric characters so ewallet providers can format however they wish.

- Do we need to fix the length? Can we make the length flexible and let each ewallet provider decides on their own? For example, `omgo-1234-5678` might work for us, while others might want `ghub-1234-5678-9012-3456` or more. Given that there's a check digit it's still possible to detect input completion without knowing the length.

- Could this address format be future-proof? E.g. plan for digit expansion. Would we extend by prepending or appending? This might affect the check digit especially ISO 7064 that involves moving some digits from front to back as part of the check 😓.

- Off-topic: For non-custodial wallets, i.e. the wallet has a blockchain address, this address format we're discussing could also be used as the alias to the blockchain address maybe? Given if the provider can provide `provider address -> blockchain address` discovery service for their users?

-----

**Nay:**
- **UUID and ULIDs:** They are hard to distinguish/comprehend visually, let alone input by hand. While it's great as record identifiers, I think we need something more user-friendly for wallet addresses that users will be interacting with them all the time.
- **Mnemonic phrases:** I find them really slow to input and way too long to be used in user interfaces, both for displaying and inputting. They're okay as recovery phrases.
- **`bbb-t-nnnnn-c` Thai bank account format:** I believe it's being obsoleted because of the limited space. And since our focus is not specifically Thailand, the credit card number variants are easily more superior.

**Comment by sirn** [comment]
If we want to go with numbers, might be worth revisiting [how humans remember numbers](https://www.quora.com/Is-it-actually-true-that-the-average-person-can-only-memorise-7-digits-at-a-time)

**Comment by jet86** [comment]
My preference would be Option 3 with check digits, but there are 2 considerations I'm trying to work out how to handle:

How are the addresses generated? If the addresses are generated at random, then that avoids the scam/abuse vector of people using the first 4 chars to claim to be someone they aren't, but it also means people can't legitimately use the 4 chars in a meaningful way either. If users are able to choose/request an address, how would that be maintained and managed in a public, trustless system?
